# Generated by Django 4.1.5 on 2023-01-31 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0003_remove_user_name_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_passengers',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='special_vehicle_info',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Sports Car', 'Sports Car'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'Sport Utility Vehicle'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan'), ('Truck', 'Pickup Truck')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
