# Generated by Django 4.1.5 on 2023-02-01 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0004_user_firstname_user_lastname_user_max_passengers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Coupe', 'Coupe'), ('SUV', 'Sport Utility Vehicle'), ('Minivan', 'Minivan'), ('Truck', 'Pickup Truck'), ('Crossover', 'Crossover'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Sports Car', 'Sports Car'), ('Convertible', 'Convertible')], max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=512)),
                ('arrival', models.DateTimeField()),
                ('passenger_num', models.IntegerField()),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'open'), ('complete', 'complete'), ('confirmed', 'confirmed')], default='open', max_length=32)),
                ('special_requests', models.CharField(blank=True, max_length=512, null=True)),
                ('requested_vehicle_type', models.CharField(blank=True, choices=[('Coupe', 'Coupe'), ('SUV', 'Sport Utility Vehicle'), ('Minivan', 'Minivan'), ('Truck', 'Pickup Truck'), ('Crossover', 'Crossover'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Sports Car', 'Sports Car'), ('Convertible', 'Convertible')], max_length=64, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='ride_sharing_service.user')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='ride_sharing_service.user')),
                ('sharers', models.ManyToManyField(blank=True, related_name='sharer', to='ride_sharing_service.user')),
            ],
        ),
    ]
