# Generated by Django 4.1.5 on 2023-02-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0005_alter_user_max_passengers_alter_user_vehicle_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='arrival',
        ),
        migrations.AddField(
            model_name='ride',
            name='arrival_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('SUV', 'Sport Utility Vehicle'), ('Sports Car', 'Sports Car'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Truck', 'Pickup Truck'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('SUV', 'Sport Utility Vehicle'), ('Sports Car', 'Sports Car'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Truck', 'Pickup Truck'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible')], max_length=64, null=True),
        ),
    ]
