# Generated by Django 4.1.5 on 2023-02-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0006_remove_ride_arrival_ride_arrival_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='arrival_date',
            new_name='arrival',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='arrival_time',
        ),
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Crossover', 'Crossover'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Sports Car', 'Sports Car'), ('SUV', 'Sport Utility Vehicle'), ('Minivan', 'Minivan'), ('Truck', 'Pickup Truck')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('complete', 'complete'), ('open', 'open')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Crossover', 'Crossover'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Sports Car', 'Sports Car'), ('SUV', 'Sport Utility Vehicle'), ('Minivan', 'Minivan'), ('Truck', 'Pickup Truck')], max_length=64, null=True),
        ),
    ]
