# Generated by Django 4.1.5 on 2023-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0011_alter_ride_requested_vehicle_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='special_requests',
            new_name='special_request',
        ),
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Truck', 'Pickup Truck'), ('Coupe', 'Coupe'), ('Sports Car', 'Sports Car'), ('Minivan', 'Minivan'), ('SUV', 'Sport Utility Vehicle'), ('Crossover', 'Crossover')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Truck', 'Pickup Truck'), ('Coupe', 'Coupe'), ('Sports Car', 'Sports Car'), ('Minivan', 'Minivan'), ('SUV', 'Sport Utility Vehicle'), ('Crossover', 'Crossover')], max_length=64, null=True),
        ),
    ]
