# Generated by Django 4.1.5 on 2023-02-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0012_rename_special_requests_ride_special_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='sharers',
            new_name='sharer',
        ),
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Convertible', 'Convertible'), ('SUV', 'Sport Utility Vehicle'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Sports Car', 'Sports Car'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Truck', 'Pickup Truck')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('open', 'open'), ('complete', 'complete')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Convertible', 'Convertible'), ('SUV', 'Sport Utility Vehicle'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Sports Car', 'Sports Car'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Truck', 'Pickup Truck')], max_length=64, null=True),
        ),
    ]
