# Generated by Django 4.1.5 on 2023-02-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0013_rename_sharers_ride_sharer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Crossover', 'Crossover'), ('Hatchback', 'Hatchback'), ('Sports Car', 'Sports Car'), ('SUV', 'Sport Utility Vehicle'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Truck', 'Pickup Truck'), ('Minivan', 'Minivan'), ('Convertible', 'Convertible')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Open', 'Cpen'), ('Complete', 'Complete'), ('Confirmed', 'Confirmed')], default='Open', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Crossover', 'Crossover'), ('Hatchback', 'Hatchback'), ('Sports Car', 'Sports Car'), ('SUV', 'Sport Utility Vehicle'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Truck', 'Pickup Truck'), ('Minivan', 'Minivan'), ('Convertible', 'Convertible')], max_length=64, null=True),
        ),
    ]
