# Generated by Django 4.1.5 on 2023-02-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0016_alter_ride_requested_vehicle_type_alter_ride_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Crossover', 'Crossover'), ('SUV', 'Sport Utility Vehicle'), ('Convertible', 'Convertible'), ('Minivan', 'Minivan'), ('Sports Car', 'Sports Car'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Truck', 'Pickup Truck'), ('Coupe', 'Coupe')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Complete', 'Complete'), ('Confirmed', 'Confirmed')], default='Open', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Crossover', 'Crossover'), ('SUV', 'Sport Utility Vehicle'), ('Convertible', 'Convertible'), ('Minivan', 'Minivan'), ('Sports Car', 'Sports Car'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Truck', 'Pickup Truck'), ('Coupe', 'Coupe')], max_length=64, null=True),
        ),
    ]
