# Generated by Django 4.1.5 on 2023-02-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0017_alter_ride_arrival_alter_ride_requested_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('SUV', 'Sport Utility Vehicle'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan'), ('Minivan', 'Minivan'), ('Coupe', 'Coupe'), ('Truck', 'Pickup Truck'), ('Hatchback', 'Hatchback'), ('Sports Car', 'Sports Car')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Open', 'Open'), ('Complete', 'Complete')], default='Open', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('SUV', 'Sport Utility Vehicle'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan'), ('Minivan', 'Minivan'), ('Coupe', 'Coupe'), ('Truck', 'Pickup Truck'), ('Hatchback', 'Hatchback'), ('Sports Car', 'Sports Car')], max_length=64, null=True),
        ),
    ]
