# Generated by Django 4.1.6 on 2023-02-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0026_merge_20230205_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Truck', 'Pickup Truck'), ('Sports Car', 'Sports Car'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan'), ('Hatchback', 'Hatchback'), ('SUV', 'Sport Utility Vehicle'), ('Sedan', 'Sedan')], default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Truck', 'Pickup Truck'), ('Sports Car', 'Sports Car'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan'), ('Hatchback', 'Hatchback'), ('SUV', 'Sport Utility Vehicle'), ('Sedan', 'Sedan')], max_length=64, null=True),
        ),
    ]
