# Generated by Django 4.1.5 on 2023-02-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0027_alter_ride_requested_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Crossover', 'Crossover'), ('Hatchback', 'Hatchback'), ('SUV', 'Sport Utility Vehicle'), ('Truck', 'Pickup Truck'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Minivan', 'Minivan'), ('Sports Car', 'Sports Car')], default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Open', 'Open'), ('Completed', 'Completed')], default='Open', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Crossover', 'Crossover'), ('Hatchback', 'Hatchback'), ('SUV', 'Sport Utility Vehicle'), ('Truck', 'Pickup Truck'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Minivan', 'Minivan'), ('Sports Car', 'Sports Car')], max_length=64, null=True),
        ),
    ]
