# Generated by Django 4.1.5 on 2023-02-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0028_alter_ride_requested_vehicle_type_alter_ride_status_and_more'),
        ('ride_sharing_service', '0028_alter_ride_requested_vehicle_type_and_more'),
    ]

    operations = [
    ]
