# Generated by Django 4.1.5 on 2023-02-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0031_alter_ride_requested_vehicle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ride_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_sharer_passenger_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Minivan', 'Minivan'), ('Sports Car', 'Sports Car'), ('Truck', 'Pickup Truck'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('SUV', 'Sport Utility Vehicle')], default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Confirmed', 'Confirmed'), ('Open', 'Open')], default='Open', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Minivan', 'Minivan'), ('Sports Car', 'Sports Car'), ('Truck', 'Pickup Truck'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('SUV', 'Sport Utility Vehicle')], max_length=64, null=True),
        ),
    ]
