# Generated by Django 4.1.5 on 2023-02-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0031_alter_ride_requested_vehicle_type_alter_ride_status_and_more'),
        ('ride_sharing_service', '0032_sharer_user_ride_id_user_temp_sharer_passenger_num_and_more'),
    ]

    operations = [
    ]
