# Generated by Django 4.1.5 on 2023-02-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0033_merge_20230206_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ride_id',
        ),
        migrations.AddField(
            model_name='sharer',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='ride_sharing_service.ride'),
        ),
        migrations.AddField(
            model_name='sharer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='ride_sharing_service.user'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Convertible', 'Convertible'), ('SUV', 'Sport Utility Vehicle'), ('Truck', 'Pickup Truck'), ('Minivan', 'Minivan'), ('Coupe', 'Coupe'), ('Crossover', 'Crossover'), ('Hatchback', 'Hatchback'), ('Sports Car', 'Sports Car')], default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Convertible', 'Convertible'), ('SUV', 'Sport Utility Vehicle'), ('Truck', 'Pickup Truck'), ('Minivan', 'Minivan'), ('Coupe', 'Coupe'), ('Crossover', 'Crossover'), ('Hatchback', 'Hatchback'), ('Sports Car', 'Sports Car')], max_length=64, null=True),
        ),
    ]
