# Generated by Django 4.1.5 on 2023-02-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0035_sharer_joined_alter_ride_requested_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Truck', 'Pickup Truck'), ('SUV', 'Sport Utility Vehicle'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Sports Car', 'Sports Car')], default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Confirmed', 'Confirmed'), ('Open', 'Open')], default='Open', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Truck', 'Pickup Truck'), ('SUV', 'Sport Utility Vehicle'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Sports Car', 'Sports Car')], max_length=64, null=True),
        ),
    ]
