# Generated by Django 4.1.6 on 2023-02-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_service', '0036_alter_ride_requested_vehicle_type_alter_ride_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'Sport Utility Vehicle'), ('Convertible', 'Convertible'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Truck', 'Pickup Truck'), ('Hatchback', 'Hatchback'), ('Sports Car', 'Sports Car'), ('Coupe', 'Coupe')], default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Open', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'Sport Utility Vehicle'), ('Convertible', 'Convertible'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Truck', 'Pickup Truck'), ('Hatchback', 'Hatchback'), ('Sports Car', 'Sports Car'), ('Coupe', 'Coupe')], max_length=64, null=True),
        ),
    ]
